### ISSUE TITLE
general issues regarding missing .xproj

### ISSUE THREAD

**Issue by atsushieno** [mrward/monodevelop-dnx-addin#17] opened 2016-01-19 10:11 UTC
(1) Create a ASP.NET Console project, then close and reopen it. It fails to open because the project .xproj does not exist.

(2) The issue above is likely because monodevelop now doesn't "save" project automatically when it was created. So, I tried to rename Program.cs to trigger save operation in monodevelop. But that results in an error dialog saying:

> Save failed.
> 
> Method 'MSBuildProject.AddNewPropertyGroup' not found."

It is from monodevelop a9780db (master) and monodevelop-dnx-addin c941d59 (roslyn) on Ubuntu 14.04.

In case dnx matters...

atsushi:/svn/monodevelop$ dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         Mono
 Architecture: x64
 OS Name:      Linux
 OS Version:   ubuntu 14.04
 Runtime Id:   ubuntu.14.04-x64

**Comment by mrward** [comment] 2016-01-19 21:13
Not sure what the problem is here. The MonoDevelop API has changed so the dnx addin on the roslyn branch was not compiling. That is now fixed. I cannot reproduce the problem with the .xproj not being saved.

**Closed as completed** 2019-09-14 17:23 UTC
